const state={lang:localStorage.getItem("ultimate-lang")||(navigator.language.startsWith("zh")?"zh":"en")};
const tx=(en,zh)=>state.lang==="zh"?zh:en;
async function load(p){return fetch((window.BASE||"")+p).then(r=>r.json())}
function header(){const b=window.BASE||"";return `<header class="header"><div class="container nav"><a class="brand" href="${b}index.html"><b>YEN-WEN LU</b><small>${tx("INTELLIGENT MICROSYSTEMS WITH REAL-WORLD IMPACT","以智慧微系統創造真實世界的影響")}</small></a><button class="menu" id="menu">☰</button><nav class="links" id="links"><a href="${b}index.html">${tx("Home","首頁")}</a><a href="${b}about.html">${tx("About","關於")}</a><a href="${b}research.html">${tx("Research","研究")}</a><a href="${b}publications.html">${tx("Publications","著作")}</a><a href="${b}teaching.html">${tx("Teaching","教學")}</a><a href="${b}people.html">${tx("People","團隊")}</a><a href="${b}collaboration.html">${tx("Collaboration","合作")}</a><a href="${b}join.html">${tx("Join Us","加入我們")}</a><button class="lang" id="lang">${state.lang==="zh"?"EN":"中文"}</button></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="container footer-row"><div><b>Yen-Wen Lu</b><div>${tx("Microfluidics & Intelligent Microsystems Laboratory · National Taiwan University","微流體與智慧微系統研究團隊 · 國立臺灣大學")}</div><a class="footer-email" href="mailto:yenwenlu@ntu.edu.tw">yenwenlu@ntu.edu.tw</a></div><div>© ${new Date().getFullYear()}</div></div></footer>`}
function initShell(){const b=window.BASE||"";["enhancements.css","story.css"].forEach(x=>{if(!document.querySelector(`link[href$="${x}"]`))document.head.insertAdjacentHTML("beforeend",`<link rel="stylesheet" href="${b}${x}">`)});document.querySelector("#header").innerHTML=header();document.querySelector("#footer").innerHTML=footer();document.querySelector("#menu").onclick=()=>document.querySelector("#links").classList.toggle("open");document.querySelector("#lang").onclick=()=>{state.lang=state.lang==="zh"?"en":"zh";localStorage.setItem("ultimate-lang",state.lang);location.reload()}}
function researchCard(p){const b=window.BASE||"";return `<article class="card research-card"><img class="card-img" src="${b}${p.image}" alt=""><div class="card-body"><p class="eyebrow-small">${tx(p.tagline,p.taglineZh)}</p><h3>${tx(p.title,p.titleZh)}</h3><p>${tx(p.why,p.whyZh).slice(0,170)}…</p><p class="connection"><b>${tx("Connects to:","連結至：")}</b> ${tx(p.connects,p.connectsZh)}</p><a class="text-link" href="${b}research/${p.id}.html">${tx("Explore this platform →","深入了解 →")}</a></div></article>`}
function personCard(p){const b=window.BASE||"";return `<article class="card"><img class="card-img" src="${b}${p.image}" alt=""><div class="card-body"><span class="pill">${tx(p.role,p.roleZh)}</span><h3>${tx(p.name,p.nameZh)}</h3><p>${tx(p.bio,p.bioZh)}</p><a class="text-link" href="${b}people/${p.id}.html">${tx("View profile →","查看資料 →")}</a></div></article>`}
const stories={
 "digital-microfluidics":{zh:"從一滴血或少量檢體到可信賴的判讀，真正困難的往往不是單一檢測反應，而是前面的取樣、混合、分離與定量。傳統流程仰賴幫浦、管線與人工操作；微流體與數位微流體則把這些步驟濃縮在晶片上，讓液滴在電極引導下移動、混合與分裂。團隊也以聲流體減少過濾時的阻塞，讓珍貴細胞或法醫樣品不因等待而流失。這不只是把設備縮小，而是在建立更少試劑、更少步驟、可被量產與帶到現場的生物分析方式。",en:"Turning a drop of blood or a scarce sample into a trustworthy result is not only about the final assay. Sampling, mixing, separation, and quantification are often the real obstacles. Conventional workflows require pumps, tubing, and careful manual steps. Our microfluidic and digital-microfluidic systems place these operations on a chip, where droplets can move, mix, and divide under programmed electrodes. Acoustofluidic filtration helps prevent clogging so precious cells and forensic samples are not lost while waiting. The goal is not merely a smaller instrument, but a simpler, lower-reagent, field-ready way to perform biological analysis."},
 "wearable-sensors":{zh:"許多健康變化不會剛好發生在門診時間：疲勞、姿勢失衡、脈搏細節、壓力或代謝狀態，往往在日常生活中才最真實。穿戴式感測的挑戰，是讓裝置像衣物或皮膚的一部分，同時仍能穩定辨識微小訊號。團隊以紙基、摺紙結構與導電奈米材料放大觸覺與生理訊號，並結合低功耗與自供電概念，降低長時間使用的負擔。這些研究讓一般人也能理解：好的健康科技不只追求更多數據，而是以舒適、可靠且可負擔的方式，陪伴人們看見身體的變化。",en:"Many meaningful health changes do not occur during a clinic visit. Fatigue, posture imbalance, pulse detail, stress, and metabolic change are often most visible in everyday life. Wearable sensing must therefore feel like part of clothing or skin while still detecting very small signals reliably. Our work uses paper substrates, origami structures, and conductive nanomaterials to amplify tactile and physiological information, together with low-power and self-powered concepts for longer use. It offers a simple public lesson: useful health technology is not about collecting more data alone, but about making body signals comfortable, reliable, and affordable to understand."},
 "ai-hemodialysis":{zh:"一場血液透析通常持續數小時，但臨床人員能即時掌握的資訊有限；病人的尿毒素清除、身體反應與低血壓風險，可能在療程中逐步改變。團隊把多波長光學感測器設置於透析廢液端，每分鐘讀取訊號，再結合病人特徵與機器學習，嘗試把看似抽象的光吸收曲線轉化為有臨床意義的指標。這項研究讓一般讀者看見 AI 在醫療中的角色：不是取代醫師，而是把連續而複雜的資料整理成較早、較個人化的提醒，協助醫療團隊更理解每一次治療。",en:"A hemodialysis session lasts for hours, yet the information available in real time is limited. Toxin removal, physiological response, and hypotension risk can all change during treatment. Our team places multi-wavelength optical sensing at the spent-dialysate outlet, reads signals every minute, and combines them with patient-specific variables and machine learning. The aim is to turn an abstract absorption curve into clinically meaningful information. For the public, this illustrates AI's proper role in medicine: not replacing clinicians, but organising continuous, complex data into earlier and more personalised prompts that help the care team understand each treatment."},
 "soft-robotics":{zh:"當機器人接觸人體、細胞或農作物時，力量並非越大越好；更重要的是能否安全、柔順而精準地回應環境。團隊以磁性軟材料設計可程式化的仿生運動，從微型手部操控到軟性抓取，探索如何把感測、材料與控制結合。同時，研究也延伸到高功率系統的熱流管理：電池與電子設備若有熱點或氣流不均，可靠度便會下降。這兩類工作共享同一個問題——如何讓系統在真實且變動的環境中更有適應力，並更有效率地使用材料與能源。",en:"When robots interact with people, cells, or crops, greater force is not always better. What matters is responding safely, gently, and precisely to the environment. We use magnetic soft materials to programme biomimetic motion, from microhand manipulation to compliant grasping, while exploring how sensing, materials, and control can work together. The same thinking extends to thermal-fluid management in high-power systems: batteries and electronics lose reliability when hot spots and uneven airflow persist. Both lines ask one question—how can a system adapt better in a changing real environment while using materials and energy more efficiently?"}
};
const publicLearning={
 "digital-microfluidics":["Watch how a droplet becomes a programmable laboratory.","Compare a pipette workflow with a lab-on-a-chip workflow.","Ask why small sample volumes can improve access to testing."],
 "wearable-sensors":["Notice how pressure, motion, and pulse create different physical signals.","Explore why a sensor must balance sensitivity with comfort.","Consider what makes personal data useful and responsible."],
 "ai-hemodialysis":["Follow the path from a light signal to a clinical estimate.","Learn why data must be interpreted with patient context.","Discuss how AI can support—not replace—clinical judgement."],
 "soft-robotics":["See how material choice can change the way a robot moves.","Compare rigid precision with soft, safe interaction.","Explore why heat and airflow matter to reliable energy systems."]
};
const publicLearningZh={
 "digital-microfluidics":["看一滴液體如何成為可程式化的小型實驗室。","比較傳統移液與實驗室晶片的操作流程。","思考少量樣品為何可能讓檢測更容易被使用。"],
 "wearable-sensors":["觀察壓力、動作與脈搏如何形成不同的物理訊號。","理解感測器為何必須在靈敏度與舒適間取得平衡。","思考個人健康資料如何才算有用且負責任。"],
 "ai-hemodialysis":["跟著光學訊號走到臨床估測值的過程。","理解資料為何必須放在病人脈絡中解讀。","討論 AI 如何支援、而非取代，臨床判斷。"],
 "soft-robotics":["觀察材料選擇如何改變機器人的運動方式。","比較剛性精準與軟性安全互動的差異。","探索熱與氣流為何影響能源系統的可靠度。"]
};
function embeddedVideos(p){if(!p.media?.length)return "";return `<section class="section video-section"><div class="container"><p class="kicker">WATCH & LEARN</p><h2>${tx("See the idea in motion","直接觀看研究影片")}</h2><div class="video-grid">${p.media.map(m=>`<article class="video-card"><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/${m.videoId}" title="${tx(m.title,m.titleZh)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div><h3>${tx(m.title,m.titleZh)}</h3><p>${tx(m.description,m.descriptionZh)}</p></div></article>`).join("")}</div></div></section>`}
function renderResearchPage(id){load("data/research.json").then(d=>{const p=d.find(x=>x.id===id);if(!p)return;tag.textContent=tx(p.tagline,p.taglineZh);title.textContent=tx(p.title,p.titleZh);lead.textContent=tx(p.why,p.whyZh);img.src="../"+p.image;story.textContent=tx(stories[id].en,stories[id].zh);evidence.innerHTML=tx(p.evidence,p.evidenceZh).map(x=>`<div class="metric"><b>${x}</b></div>`).join("");learnTitle.textContent=tx("For curious readers","給想多了解的讀者");learn.innerHTML=tx(publicLearning[id],publicLearningZh[id]).map(x=>`<div class="learn-item">${x}</div>`).join("");document.querySelector("main").insertAdjacentHTML("beforeend",embeddedVideos(p))})}
